### ISSUE TITLE
Unexpected error: java.lang.NullPointerException: Server URL is null!

### ISSUE THREAD

**Issue by zinuo-H** [boecker-lab/sirius#101]
Hi Sirius Team,

I installed SIRIUS-5.6.3 (CLI only) on my school's Linux cluster(Centos Linux 7.6 64 bit) and try to run the demo data from "Quick start CLI - Example 1: MGF". 

However, I can only get these results without <structrue_candudates.tsv> file:
<img width="793" alt="image" src="https://user-images.githubusercontent.com/81279360/216967763-ed85fc13-90ec-445e-bdd8-aa2618cf85fd.png">

It seems like this job failed when generating the fingerprint.

```
WARNING 17:41:00 - <9>[FingerblastSubToolJob-9 | <Awaiting Instance>] Required Job 'FingerprintSubToolJob-8 | 1_laudanosine_FEATURE_1@358m/z' finished with unexpected state 'FAILED'.
WARNING 17:41:00 - <10>[CanopusSubToolJob-10 | <Awaiting Instance>] Required Job 'FingerblastSubToolJob-9 | <Awaiting Instance>' finished with unexpected state 'CANCELED'.
SEVERE  17:41:00 - <8>[FingerprintSubToolJob-8 | 1_laudanosine_FEATURE_1@358m/z] Failed!
java.lang.NullPointerException: Server URL is null!
	at de.unijena.bioinf.ms.rest.client.AbstractClient.getBaseURI(AbstractClient.java:259)
	at de.unijena.bioinf.ms.rest.client.AbstractCsiClient.getBaseURI(AbstractCsiClient.java:82)
	at de.unijena.bioinf.ms.rest.client.AbstractCsiClient.buildWebapiURI(AbstractCsiClient.java:70)
	at de.unijena.bioinf.ms.rest.client.AbstractCsiClient.buildVersionSpecificWebapiURI(AbstractCsiClient.java:74)
	at de.unijena.bioinf.ms.rest.client.fingerid.FingerIdClient.lambda$getFingerIdData$1(FingerIdClient.java:91)
	at de.unijena.bioinf.ms.rest.client.AbstractClient.execute(AbstractClient.java:140)
	at de.unijena.bioinf.ms.rest.client.fingerid.FingerIdClient.getFingerIdData(FingerIdClient.java:90)
	at de.unijena.bioinf.webapi.rest.RestAPI.lambda$getFingerIdDataUncached$26(RestAPI.java:428)
	at de.unijena.bioinf.rest.ProxyManager.applyClient(ProxyManager.java:547)
	at de.unijena.bioinf.rest.ProxyManager.applyClient(ProxyManager.java:541)
	at de.unijena.bioinf.webapi.rest.RestAPI.getFingerIdDataUncached(RestAPI.java:428)
	at de.unijena.bioinf.webapi.AbstractWebAPI.lambda$getFingerIdData$1(AbstractWebAPI.java:81)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at de.unijena.bioinf.webapi.AbstractWebAPI.getFingerIdData(AbstractWebAPI.java:79)
	at de.unijena.bioinf.ms.frontend.subtools.fingerprint.FingerprintSubToolJob.lambda$computeAndAnnotateResult$1(FingerprintSubToolJob.java:83)
	at de.unijena.bioinf.rest.NetUtils.tryAndWait(NetUtils.java:93)
	at de.unijena.bioinf.rest.NetUtils.tryAndWait(NetUtils.java:85)
	at de.unijena.bioinf.ms.frontend.subtools.fingerprint.FingerprintSubToolJob.computeAndAnnotateResult(FingerprintSubToolJob.java:83)
	at de.unijena.bioinf.ms.frontend.subtools.InstanceJob.compute(InstanceJob.java:80)
	at de.unijena.bioinf.ms.frontend.subtools.InstanceJob.compute(InstanceJob.java:44)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:117)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

- The full error output can be found in this file: https://drive.google.com/drive/folders/1BHg1woNrMtOuYa3gjvuRAa-yS07BY-WK?usp=share_link 
 
I don't know what happens when I run Sirius on this Linux platform. I can run this demo data successfully on my personal macOS computer. 

Hope for your advice and help!

Thank you!

**Comment by mfleisch** [comment]
Are you logged in?  If not please check `sirius login -h`  for details.

**Comment by zinuo-H** [comment]
> Are you logged in? If not please check `sirius login -h` for details.

Thank you so much💕! The problem has been solved after logging in.
