### ISSUE TITLE
unexpected error when starting sirius

### ISSUE THREAD

**Issue by AndreaCa96** [boecker-lab/sirius#102]
I got unexpected errors below when starting "sirius-gui.exe" in my mac (fine on my laptot with Windows). Tried to update JAVA but problem remains. Any ideas on how to fix this? Thanks!

Unexpected error!
java.lang.NullPointerException
    at java.base/java.util.Objects.requireNonNull(Unknown Source)
    at java.base/sun.nio.fs.UnixFileSystem.getPath(Unknown Source)
    at java.base/java.nio.file.Path.of(Unknown Source)
    at java.base/java.nio.file.Paths.get(Unknown Source)
    at de.unijena.bioinf.chemdb.SearchableDatabases.getDatabaseDirectory(SearchableDatabases.java:76)
    at de.unijena.bioinf.chemdb.SearchableDatabases.getCustomDatabaseDirectory(SearchableDatabases.java:57)
    at de.unijena.bioinf.chemdb.SearchableDatabases.loadCustomDatabases(SearchableDatabases.java:171)
    at de.unijena.bioinf.chemdb.SearchableDatabases.getCustomDatabases(SearchableDatabases.java:153)
    at de.unijena.bioinf.chemdb.SearchableDatabases.getCustomDatabases(SearchableDatabases.java:148)
    at de.unijena.bioinf.chemdb.SearchableDatabases.getAvailableDatabases(SearchableDatabases.java:164)
    at de.unijena.bioinf.ms.frontend.subtools.gui.GuiAppOptions$Flow$2.compute(GuiAppOptions.java:142)
    at de.unijena.bioinf.ms.frontend.subtools.gui.GuiAppOptions$Flow$2.compute(GuiAppOptions.java:133)
    at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:117)
    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)

**Comment by mfleisch** [comment]
`sirius-gui.exe` is a window executable and  only part of the windows version. Please download and install the mac version instead.
e.g. here: https://github.com/bright-giant/sirius/releases/download/v5.6.3/sirius-5.6.3-osx64.pkg

Please reopen if this does not solve your issue.

**Comment by AndreaCa96** [comment]
I did installed the mac version but i had always the same error:

Unexpected error!
java.lang.NullPointerException
at java.base/java.util.Objects.requireNonNull(Unknown Source)
at java.base/sun.nio.fs.UnixFileSystem.getPath(Unknown Source)
at java.base/java.nio.file.Path.of(Unknown Source)
at java.base/java.nio.file.Paths.get(Unknown Source)
at de.unijena.bioinf.chemdb.SearchableDatabases.getDatabaseDirectory(SearchableDatabases.java:76)
at de.unijena.bioinf.chemdb.SearchableDatabases.getCustomDatabaseDirectory(SearchableDatabases.java:57)
at de.unijena.bioinf.chemdb.SearchableDatabases.loadCustomDatabases(SearchableDatabases.java:171)
at de.unijena.bioinf.chemdb.SearchableDatabases.getCustomDatabases(SearchableDatabases.java:153)
at de.unijena.bioinf.chemdb.SearchableDatabases.getCustomDatabases(SearchableDatabases.java:148)
at de.unijena.bioinf.chemdb.SearchableDatabases.getAvailableDatabases(SearchableDatabases.java:164)
at de.unijena.bioinf.ms.frontend.subtools.gui.GuiAppOptions$Flow$2.compute(GuiAppOptions.java:142)
at de.unijena.bioinf.ms.frontend.subtools.gui.GuiAppOptions$Flow$2.compute(GuiAppOptions.java:133)
at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:117)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
