### ISSUE TITLE
Unexpected error!

### ISSUE THREAD

**Issue by AndreaCa96** [boecker-lab/sirius#103]
got unexpected errors below when starting sirius on my mac. Tried to update JAVA but problem remains. Any ideas on how to fix this? Thanks!

Unexpected error!
java.lang.NullPointerException
at java.base/java.util.Objects.requireNonNull(Unknown Source)
at java.base/sun.nio.fs.UnixFileSystem.getPath(Unknown Source)
at java.base/java.nio.file.Path.of(Unknown Source)
at java.base/java.nio.file.Paths.get(Unknown Source)
at de.unijena.bioinf.chemdb.SearchableDatabases.getDatabaseDirectory(SearchableDatabases.java:76)
at de.unijena.bioinf.chemdb.SearchableDatabases.getCustomDatabaseDirectory(SearchableDatabases.java:57)
at de.unijena.bioinf.chemdb.SearchableDatabases.loadCustomDatabases(SearchableDatabases.java:171)
at de.unijena.bioinf.chemdb.SearchableDatabases.getCustomDatabases(SearchableDatabases.java:153)
at de.unijena.bioinf.chemdb.SearchableDatabases.getCustomDatabases(SearchableDatabases.java:148)
at de.unijena.bioinf.chemdb.SearchableDatabases.getAvailableDatabases(SearchableDatabases.java:164)
at de.unijena.bioinf.ms.frontend.subtools.gui.GuiAppOptions$Flow$2.compute(GuiAppOptions.java:142)
at de.unijena.bioinf.ms.frontend.subtools.gui.GuiAppOptions$Flow$2.compute(GuiAppOptions.java:133)
at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:117)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)

**Comment by mfleisch** [comment]
Can you please try deleting (or moving) the `.sirius-5.6` directory in your user home and try again.

**Comment by AndreaCa96** [comment]
Now it works!
