### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by kuntuse** [boecker-lab/sirius#104]
Hi,
I am using CLI version 5.6.3. When i run the programe, Ifind that fingerprint dose not work. 

### SEVERE  16:15:13 - <13221903>[FingerprintSubToolJob-13221903 | 30511_50_types_pos_3168@321m/z] ToolChain Job failed due to: java.lang.NullPointerException: Server URL is null!

I realized that I might not be logged in. I tried to log in, but it shows Connection error. The network connection problem did not occur during the previous analysis.

### Enter value for --password (Console password input.): 
INFO    16:17:05 - Job manager successful initialized with 13 CPU thread(s) and 4 IO thread(s).
INFO    16:17:06 - Starting http Client with MaxPerRout=4 / maxTotal=5(Threads=13).
WARNING 16:17:10 - Could not reach secured api endpoint. Bad Response Code. Cause: Error when querying REST service. Bad Response Code: 503 | Message: Service Temporarily Unavailable | Content: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

WARNING 16:17:13 - Could not load version info (unsecured api endpoint). Bad Response Code. Cause: Error when querying REST service. Bad Response Code: 503 | Message: Service Temporarily Unavailable | Content: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

INFO    16:17:26 - Recoverable I/O exception (java.net.SocketException) caught when processing request to {s}->https://www.google.com:443
WARNING 16:17:37 - Connection error
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory$1.run(SSLConnectionSocketFactory.java:219)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:216)
	at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:148)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:396)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:158)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:168)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:136)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:175)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:75)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:89)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:54)
	at de.unijena.bioinf.rest.ProxyManager.checkConnectionToUrl(ProxyManager.java:373)
	at de.unijena.bioinf.rest.ProxyManager.checkExternal(ProxyManager.java:350)
	at de.unijena.bioinf.rest.ProxyManager.checkInternetConnection(ProxyManager.java:171)
	at de.unijena.bioinf.webapi.rest.RestAPI.lambda$checkConnection$12(RestAPI.java:230)
	at de.unijena.bioinf.rest.ProxyManager.consumeClient(ProxyManager.java:521)
	at de.unijena.bioinf.rest.ProxyManager.consumeClient(ProxyManager.java:515)
	at de.unijena.bioinf.webapi.rest.RestAPI.checkConnection(RestAPI.java:223)
	at de.unijena.bioinf.ms.frontend.subtools.login.LoginOptions$LoginWorkflow.determineAndCheckActiveSubscription(LoginOptions.java:336)
	at de.unijena.bioinf.ms.frontend.subtools.login.LoginOptions$LoginWorkflow.run(LoginOptions.java:224)
	at de.unijena.bioinf.ms.frontend.Run.compute(Run.java:61)
	at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.run(SiriusCLIApplication.java:131)
	at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.runMain(SiriusCLIApplication.java:73)
	at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.main(SiriusCLIApplication.java:53)

**Comment by kuntuse** [comment]
In GUL, it shows:
![image](https://user-images.githubusercontent.com/122350213/218980172-e30e8ed3-1cd0-48b7-99c0-acd77c545c71.png)
