### ISSUE TITLE
ftree-export does could not parse compounds

### ISSUE THREAD

**Issue by YasinEl** [boecker-lab/sirius#107]
Hello,

I am attempting to export all fragmentation trees from my project space created via the SIRIUS GUI (5.6.3) as json files. However the code given in https://boecker-lab.github.io/docs.sirius.github.io/cli-standalone/#fragmentation-tree-export-tool  (
`sirius --input <project-space> ftree-export --json --output <output-dir>`) does not seem to work. Specifically I get for all my trees `Could not parse Compound with ID '54293_dda_removed_precursorIon_FEATURE_58606' Skipping it!`. I provided the full output in the following. I am running on a Microsoft Windows 10 Pro. As I side note: It does not matter where I put the output directory (i.e. moving it outside the original project space does not help). Thank you for your time and effort.

Specifically, I  get the following output. 

```
C:\Users\Dorrestein Lab>sirius --input "C:\Users\Dorrestein Lab\AppData\Local\Temp\.sirius-tmp-project-cfbef03f-72db-4c95-8a5c-93a9d1b2e0a8" ftree-export --json --output "C:\Users\Dorrestein Lab\AppData\Local\Temp\.sirius-tmp-project-cfbef03f-72db-4c95-8a5c-93a9d1b2e0a8\tree_op"
Can't load log handler "java.util.logging.FileHandler"
java.nio.file.NoSuchFileException: C:\Users\Dorrestein Lab\.sirius-4.8\sirius.log.0.lck
java.nio.file.NoSuchFileException: C:\Users\Dorrestein Lab\.sirius-4.8\sirius.log.0.lck
        at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(Unknown Source)
        at java.base/java.nio.channels.FileChannel.open(Unknown Source)
        at java.base/java.nio.channels.FileChannel.open(Unknown Source)
        at java.logging/java.util.logging.FileHandler.openFiles(Unknown Source)
        at java.logging/java.util.logging.FileHandler.<init>(Unknown Source)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(Unknown Source)
        at java.base/java.lang.Class.newInstance(Unknown Source)
        at java.logging/java.util.logging.LogManager.createLoggerHandlers(Unknown Source)
        at java.logging/java.util.logging.LogManager$4.run(Unknown Source)
        at java.logging/java.util.logging.LogManager$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.logging/java.util.logging.LogManager.loadLoggerHandlers(Unknown Source)
        at java.logging/java.util.logging.LogManager.initializeGlobalHandlers(Unknown Source)
        at java.logging/java.util.logging.LogManager$RootLogger.accessCheckedHandlers(Unknown Source)
        at java.logging/java.util.logging.Logger.getHandlers(Unknown Source)
        at java.logging/java.util.logging.Logger.log(Unknown Source)
        at org.slf4j.impl.JDK14LoggerAdapter.log(JDK14LoggerAdapter.java:582)
        at org.slf4j.impl.JDK14LoggerAdapter.info(JDK14LoggerAdapter.java:277)
        at de.unijena.bioinf.ms.frontend.core.ApplicationCore.<clinit>(ApplicationCore.java:245)
        at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.run(SiriusCLIApplication.java:108)
        at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.main(SiriusCLIApplication.java:53)
INFO    11:24:02 - Sirius Workspace Successfull initialized at: C:\Users\Dorrestein Lab\.sirius-4.9
INFO    11:24:02 - You run SIRIUS 4.9.0
INFO    11:24:02 - Sirius was compiled with the following ILP solvers: GLPK-v1.7.0 (included), Gurobi-v9.1.1, CPLEX-v12.7.1, COIN-OR-v1.17.3
INFO    11:24:02 - Treebuilder priorities loaded from 'sirius.properties' are: [GUROBI, CPLEX, CLP, GLPK]
INFO    11:24:02 - CPU check done. 6 cores that handle 12 threads were found.
INFO    11:24:02 - Bug reporter initialized.
INFO    11:24:02 - Web API initialized.
INFO    11:24:02 - Running with following arguments: [--input, C:\Users\Dorrestein Lab\AppData\Local\Temp\.sirius-tmp-project-cfbef03f-72db-4c95-8a5c-93a9d1b2e0a8, ftree-export, --json, --output, C:\Users\Dorrestein Lab\AppData\Local\Temp\.sirius-tmp-project-cfbef03f-72db-4c95-8a5c-93a9d1b2e0a8\tree_op]
INFO    11:24:02 - Job manager successful initialized with 6 CPU thread(s) and 3 IO thread(s).
FINE    11:24:02 - <0>[InputExpanderJJob] Running post processing
FINE    11:24:02 - <0>[InputExpanderJJob] Running cleanup
INFO    11:24:02 - <1>[InputExpanderJJob] Expanding Input Files: 'C:\Users\Dorrestein Lab\AppData\Local\Temp\.sirius-tmp-project-cfbef03f-72db-4c95-8a5c-93a9d1b2e0a8'...
INFO    11:25:59 - <1>[InputExpanderJJob] ...Input Files successfully expanded!
FINE    11:25:59 - <1>[InputExpanderJJob] Running post processing
FINE    11:25:59 - <1>[InputExpanderJJob] Running cleanup
INFO    11:25:59 - No output location given. Writing output to input location: C:\Users\Dorrestein Lab\AppData\Local\Temp\.sirius-tmp-project-cfbef03f-72db-4c95-8a5c-93a9d1b2e0a8
SEVERE  11:30:09 - Could not parse Compound with ID '54293_dda_removed_precursorIon_FEATURE_58606' Skipping it!
SEVERE  11:30:09 - Could not parse Compound with ID '250219_dda_removed_precursorIon_FEATURE_266926' Skipping it!

.
.
.
.

SEVERE  11:41:09 - Could not parse Compound with ID '285568_dda_removed_precursorIon_FEATURE_309490' Skipping it!
SEVERE  11:41:09 - Could not parse Compound with ID '104452_dda_removed_precursorIon_FEATURE_112604' Skipping it!
SEVERE  11:41:09 - Could not parse Compound with ID '47599_dda_removed_precursorIon_FEATURE_51477' Skipping it!
INFO    11:41:09 - CLI shut down hook: SIRIUS is cleaning up threads and shuts down...
```

**Comment by YasinEl** [comment]
the solution was that I used the wrong CLI version of SIRIUS when calling `sirius` on the command line. calling the .exe file in the correct directory directly solved the issue
