### ISSUE TITLE
App crashes on macOS Ventura 13.0

### ISSUE THREAD

**Issue by tolimika** [boecker-lab/sirius#109]
Hi, 
I have installed Sirius on my mac yesterday. Software was working normally at first. 
But now it doesn't want to open at all. I see the small picture with "starting sirius", but then it turns off.
I've tried launching it through terminal and reinstalling, but nothing helped. 

Does someone know what could be the problem? 

Thanks in advance.

**Comment by mfleisch** [comment]
Hey, can you please post the output given when launching SIRIUS from terminal.

**Comment by tolimika** [comment]
Yes here it is: 

`Last login: Wed Mar 15 11:52:08 on ttys000
/Applications/sirius.app/Contents/MacOS/sirius ; exit;
rika@eduroam-077-080-017-040 ~ % /Applications/sirius.app/Contents/MacOS/sirius ; exit;
Mar 15, 2023 1:02:26 PM org.apache.commons.beanutils.FluentPropertyBeanIntrospector introspect
INFO: Error when creating PropertyDescriptor for public final void org.apache.commons.configuration2.AbstractConfiguration.setProperty(java.lang.String,java.lang.Object)! Ignoring this property.
INFO    13:02:28 - Sirius Workspace Successfull initialized at: /Users/rika/.sirius-5.6
INFO    13:02:28 - You run SIRIUS 5.6.3
INFO    13:02:28 - You run SIRIUS in 'GUI' mode.
INFO    13:02:28 - Sirius was compiled with the following ILP solvers: GLPK-v1.7.0 (included), Gurobi-v9.1.1, CPLEX-v12.7.1, COIN-OR-v1.17.3
INFO    13:02:28 - Treebuilder priorities loaded from 'sirius.properties' are: [CLP, GUROBI, CPLEX]
INFO    13:02:28 - CPU check done. 5 cores that handle 10 threads were found.
Application Core STATIC Block Error!
java.lang.IllegalArgumentException: Host name must not be empty
	at org.apache.hc.core5.util.Args.illegalArgumentExceptionNotEmpty(Args.java:99)
	at org.apache.hc.core5.util.Args.containsNoBlanks(Args.java:86)
	at org.apache.hc.core5.http.HttpHost.<init>(HttpHost.java:84)
	at org.apache.hc.core5.http.HttpHost.<init>(HttpHost.java:104)
	at de.unijena.bioinf.rest.ProxyManager.decorateClientBuilderWithProxySettings(ProxyManager.java:282)
	at de.unijena.bioinf.rest.ProxyManager.getClientBuilderWithProxySettings(ProxyManager.java:273)
	at de.unijena.bioinf.rest.ProxyManager.getSiriusProxyClientBuilder(ProxyManager.java:261)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpClientBuilder(ProxyManager.java:148)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpAsyncClientBuilder(ProxyManager.java:141)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpAsyncClient(ProxyManager.java:137)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpAsyncClient(ProxyManager.java:133)
	at de.unijena.bioinf.ms.frontend.core.ApplicationCore.<clinit>(ApplicationCore.java:257)
	at de.unijena.bioinf.ms.frontend.SiriusGUIApplication$1.compute(SiriusGUIApplication.java:102)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:117)
	at de.unijena.bioinf.ms.frontend.SiriusGUIApplication.main(SiriusGUIApplication.java:139)
SEVERE  13:02:28 - <0>[JJob-0] Failed!
java.lang.Exception: java.lang.ExceptionInInitializerError
	at de.unijena.bioinf.jjobs.exceptions.Exceptions.unpack(Exceptions.java:16)
	at de.unijena.bioinf.jjobs.BasicJJob.doFailHandling(BasicJJob.java:170)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:128)
	at de.unijena.bioinf.ms.frontend.SiriusGUIApplication.main(SiriusGUIApplication.java:139)
Caused by: java.lang.ExceptionInInitializerError
	at de.unijena.bioinf.ms.frontend.SiriusGUIApplication$1.compute(SiriusGUIApplication.java:102)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:117)
	... 1 more
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Host name must not be empty
	at de.unijena.bioinf.ms.frontend.core.ApplicationCore.<clinit>(ApplicationCore.java:279)
	... 3 more
Caused by: java.lang.IllegalArgumentException: Host name must not be empty
	at org.apache.hc.core5.util.Args.illegalArgumentExceptionNotEmpty(Args.java:99)
	at org.apache.hc.core5.util.Args.containsNoBlanks(Args.java:86)
	at org.apache.hc.core5.http.HttpHost.<init>(HttpHost.java:84)
	at org.apache.hc.core5.http.HttpHost.<init>(HttpHost.java:104)
	at de.unijena.bioinf.rest.ProxyManager.decorateClientBuilderWithProxySettings(ProxyManager.java:282)
	at de.unijena.bioinf.rest.ProxyManager.getClientBuilderWithProxySettings(ProxyManager.java:273)
	at de.unijena.bioinf.rest.ProxyManager.getSiriusProxyClientBuilder(ProxyManager.java:261)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpClientBuilder(ProxyManager.java:148)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpAsyncClientBuilder(ProxyManager.java:141)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpAsyncClient(ProxyManager.java:137)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpAsyncClient(ProxyManager.java:133)
	at de.unijena.bioinf.ms.frontend.core.ApplicationCore.<clinit>(ApplicationCore.java:257)
	... 3 more

FINE    13:02:28 - <0>[JJob-0] Running cleanup
java.lang.Exception: java.lang.ExceptionInInitializerError
	at de.unijena.bioinf.jjobs.exceptions.Exceptions.unpack(Exceptions.java:16)
	at de.unijena.bioinf.jjobs.BasicJJob.doFailHandling(BasicJJob.java:170)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:128)
	at de.unijena.bioinf.ms.frontend.SiriusGUIApplication.main(SiriusGUIApplication.java:139)
Caused by: java.lang.ExceptionInInitializerError
	at de.unijena.bioinf.ms.frontend.SiriusGUIApplication$1.compute(SiriusGUIApplication.java:102)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:117)
	... 1 more
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Host name must not be empty
	at de.unijena.bioinf.ms.frontend.core.ApplicationCore.<clinit>(ApplicationCore.java:279)
	... 3 more
Caused by: java.lang.IllegalArgumentException: Host name must not be empty
	at org.apache.hc.core5.util.Args.illegalArgumentExceptionNotEmpty(Args.java:99)
	at org.apache.hc.core5.util.Args.containsNoBlanks(Args.java:86)
	at org.apache.hc.core5.http.HttpHost.<init>(HttpHost.java:84)
	at org.apache.hc.core5.http.HttpHost.<init>(HttpHost.java:104)
	at de.unijena.bioinf.rest.ProxyManager.decorateClientBuilderWithProxySettings(ProxyManager.java:282)
	at de.unijena.bioinf.rest.ProxyManager.getClientBuilderWithProxySettings(ProxyManager.java:273)
	at de.unijena.bioinf.rest.ProxyManager.getSiriusProxyClientBuilder(ProxyManager.java:261)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpClientBuilder(ProxyManager.java:148)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpAsyncClientBuilder(ProxyManager.java:141)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpAsyncClient(ProxyManager.java:137)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpAsyncClient(ProxyManager.java:133)
	at de.unijena.bioinf.ms.frontend.core.ApplicationCore.<clinit>(ApplicationCore.java:257)
	... 3 more

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

`

**Comment by tolimika** [comment]
And this happens when I run it through /Applications/sirius.app/Contents/MacOS/sirius


Last login: Wed Mar 15 13:09:00 on ttys000
rika@eduroam-077-080-017-040 ~ % /Applications/sirius.app/Contents/MacOS/sirius
Mar 15, 2023 1:09:43 PM org.apache.commons.beanutils.FluentPropertyBeanIntrospector introspect
INFO: Error when creating PropertyDescriptor for public final void org.apache.commons.configuration2.AbstractConfiguration.setProperty(java.lang.String,java.lang.Object)! Ignoring this property.
INFO    13:09:44 - Sirius Workspace Successfull initialized at: /Users/rika/.sirius-5.6
INFO    13:09:44 - You run SIRIUS 5.6.3
INFO    13:09:44 - You run SIRIUS in 'GUI' mode.
INFO    13:09:44 - Sirius was compiled with the following ILP solvers: GLPK-v1.7.0 (included), Gurobi-v9.1.1, CPLEX-v12.7.1, COIN-OR-v1.17.3
INFO    13:09:44 - Treebuilder priorities loaded from 'sirius.properties' are: [CLP, GUROBI, CPLEX]
INFO    13:09:44 - CPU check done. 5 cores that handle 10 threads were found.
Application Core STATIC Block Error!
java.lang.IllegalArgumentException: Host name must not be empty
	at org.apache.hc.core5.util.Args.illegalArgumentExceptionNotEmpty(Args.java:99)
	at org.apache.hc.core5.util.Args.containsNoBlanks(Args.java:86)
	at org.apache.hc.core5.http.HttpHost.<init>(HttpHost.java:84)
	at org.apache.hc.core5.http.HttpHost.<init>(HttpHost.java:104)
	at de.unijena.bioinf.rest.ProxyManager.decorateClientBuilderWithProxySettings(ProxyManager.java:282)
	at de.unijena.bioinf.rest.ProxyManager.getClientBuilderWithProxySettings(ProxyManager.java:273)
	at de.unijena.bioinf.rest.ProxyManager.getSiriusProxyClientBuilder(ProxyManager.java:261)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpClientBuilder(ProxyManager.java:148)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpAsyncClientBuilder(ProxyManager.java:141)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpAsyncClient(ProxyManager.java:137)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpAsyncClient(ProxyManager.java:133)
	at de.unijena.bioinf.ms.frontend.core.ApplicationCore.<clinit>(ApplicationCore.java:257)
	at de.unijena.bioinf.ms.frontend.SiriusGUIApplication$1.compute(SiriusGUIApplication.java:102)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:117)
	at de.unijena.bioinf.ms.frontend.SiriusGUIApplication.main(SiriusGUIApplication.java:139)
SEVERE  13:09:44 - <0>[JJob-0] Failed!
java.lang.Exception: java.lang.ExceptionInInitializerError
	at de.unijena.bioinf.jjobs.exceptions.Exceptions.unpack(Exceptions.java:16)
	at de.unijena.bioinf.jjobs.BasicJJob.doFailHandling(BasicJJob.java:170)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:128)
	at de.unijena.bioinf.ms.frontend.SiriusGUIApplication.main(SiriusGUIApplication.java:139)
Caused by: java.lang.ExceptionInInitializerError
	at de.unijena.bioinf.ms.frontend.SiriusGUIApplication$1.compute(SiriusGUIApplication.java:102)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:117)
	... 1 more
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Host name must not be empty
	at de.unijena.bioinf.ms.frontend.core.ApplicationCore.<clinit>(ApplicationCore.java:279)
	... 3 more
Caused by: java.lang.IllegalArgumentException: Host name must not be empty
	at org.apache.hc.core5.util.Args.illegalArgumentExceptionNotEmpty(Args.java:99)
	at org.apache.hc.core5.util.Args.containsNoBlanks(Args.java:86)
	at org.apache.hc.core5.http.HttpHost.<init>(HttpHost.java:84)
	at org.apache.hc.core5.http.HttpHost.<init>(HttpHost.java:104)
	at de.unijena.bioinf.rest.ProxyManager.decorateClientBuilderWithProxySettings(ProxyManager.java:282)
	at de.unijena.bioinf.rest.ProxyManager.getClientBuilderWithProxySettings(ProxyManager.java:273)
	at de.unijena.bioinf.rest.ProxyManager.getSiriusProxyClientBuilder(ProxyManager.java:261)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpClientBuilder(ProxyManager.java:148)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpAsyncClientBuilder(ProxyManager.java:141)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpAsyncClient(ProxyManager.java:137)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpAsyncClient(ProxyManager.java:133)
	at de.unijena.bioinf.ms.frontend.core.ApplicationCore.<clinit>(ApplicationCore.java:257)
	... 3 more

FINE    13:09:44 - <0>[JJob-0] Running cleanup
java.lang.Exception: java.lang.ExceptionInInitializerError
	at de.unijena.bioinf.jjobs.exceptions.Exceptions.unpack(Exceptions.java:16)
	at de.unijena.bioinf.jjobs.BasicJJob.doFailHandling(BasicJJob.java:170)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:128)
	at de.unijena.bioinf.ms.frontend.SiriusGUIApplication.main(SiriusGUIApplication.java:139)
Caused by: java.lang.ExceptionInInitializerError
	at de.unijena.bioinf.ms.frontend.SiriusGUIApplication$1.compute(SiriusGUIApplication.java:102)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:117)
	... 1 more
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Host name must not be empty
	at de.unijena.bioinf.ms.frontend.core.ApplicationCore.<clinit>(ApplicationCore.java:279)
	... 3 more
Caused by: java.lang.IllegalArgumentException: Host name must not be empty
	at org.apache.hc.core5.util.Args.illegalArgumentExceptionNotEmpty(Args.java:99)
	at org.apache.hc.core5.util.Args.containsNoBlanks(Args.java:86)
	at org.apache.hc.core5.http.HttpHost.<init>(HttpHost.java:84)
	at org.apache.hc.core5.http.HttpHost.<init>(HttpHost.java:104)
	at de.unijena.bioinf.rest.ProxyManager.decorateClientBuilderWithProxySettings(ProxyManager.java:282)
	at de.unijena.bioinf.rest.ProxyManager.getClientBuilderWithProxySettings(ProxyManager.java:273)
	at de.unijena.bioinf.rest.ProxyManager.getSiriusProxyClientBuilder(ProxyManager.java:261)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpClientBuilder(ProxyManager.java:148)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpAsyncClientBuilder(ProxyManager.java:141)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpAsyncClient(ProxyManager.java:137)
	at de.unijena.bioinf.rest.ProxyManager.getSirirusHttpAsyncClient(ProxyManager.java:133)
	at de.unijena.bioinf.ms.frontend.core.ApplicationCore.<clinit>(ApplicationCore.java:257)
	... 3 more
rika@eduroam-077-080-017-040 ~ %

**Comment by mfleisch** [comment]
should be fixed in current version. please reopen if not.
