### ISSUE TITLE
sirius-network-connection

### ISSUE THREAD

**Issue by xdkong** [boecker-lab/sirius#144]
Dear developers,
When I use SIRIUS, the command is as follows:
/data/software/sirius-5.8.5/sirius/bin/sirius --maxmz=850 --cores 20 -i /data/kong/soybean/metabolome/mzmine_sirius.mgf -o /data/kong/soybean/metabolome/sirius_altissues11302023 formula -c 50 -p qtof -d BIO
 However, I encountered some problems, as follows:
Nov 30, 2023 4:04:45 PM de.unijena.bioinf.jjobs.JJob lambda$logError$2
SEVERE: <2869>[SiriusSubToolJob-2869 | 252_mzmine_sirius_657@785m/z] Failed!
java.lang.NullPointerException: Service URL is null. This might be caused by a missing login.
	at de.unijena.bioinf.ms.rest.client.AbstractCsiClient.getBaseURI(AbstractCsiClient.java:82)
	at de.unijena.bioinf.ms.rest.client.AbstractCsiClient.buildWebapiURI(AbstractCsiClient.java:72)
	at de.unijena.bioinf.ms.rest.client.AbstractCsiClient.buildVersionSpecificWebapiURI(AbstractCsiClient.java:76)
	at de.unijena.bioinf.ms.rest.client.chemdb.StructureSearchClient.lambda$getFormulas$1(StructureSearchClient.java:91)
	at de.unijena.bioinf.ms.rest.client.AbstractClient.execute(AbstractClient.java:133)
	at de.unijena.bioinf.ms.rest.client.chemdb.StructureSearchClient.getFormulas(StructureSearchClient.java:90)
	at de.unijena.bioinf.chemdb.RESTDatabase.lookupMolecularFormulas(RESTDatabase.java:122)
	at de.unijena.bioinf.chemdb.WebWithCustomDatabase.lambda$loadMolecularFormulas$1(WebWithCustomDatabase.java:122)
	at de.unijena.bioinf.webapi.rest.RestAPI.lambda$consumeStructureDB$19(RestAPI.java:353)
	at de.unijena.bioinf.rest.ProxyManager.consumeClient(ProxyManager.java:439)
	at de.unijena.bioinf.rest.ProxyManager.consumeClient(ProxyManager.java:432)
	at de.unijena.bioinf.webapi.rest.RestAPI.consumeStructureDB(RestAPI.java:351)
	at de.unijena.bioinf.chemdb.WebWithCustomDatabase.loadMolecularFormulas(WebWithCustomDatabase.java:121)
	at de.unijena.bioinf.chemdb.WebWithCustomDatabase.loadMolecularFormulas(WebWithCustomDatabase.java:106)
	at de.unijena.bioinf.fingerid.FormulaWhiteListJob.lambda$compute$1(FormulaWhiteListJob.java:81)
	at de.unijena.bioinf.rest.NetUtils.tryAndWait(NetUtils.java:93)
	at de.unijena.bioinf.rest.NetUtils.tryAndWait(NetUtils.java:85)
	at de.unijena.bioinf.fingerid.FormulaWhiteListJob.compute(FormulaWhiteListJob.java:80)
	at de.unijena.bioinf.fingerid.FormulaWhiteListJob.compute(FormulaWhiteListJob.java:44)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:117)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
The above is the command line I used in Linux. Also, I used the GUI version in the Windows system and encountered network connection issues：
![屏幕截图 2023-11-30 161144](https://github.com/boecker-lab/sirius/assets/10757001/0717d579-30f1-4822-ab90-9fe35b3c1690)

Best,
Xiangdong

**Comment by joXemMx** [comment]
Hi, it may be that your issue is simply caused by not being logged in correctly (see `java.lang.NullPointerException: Service URL is null. This might be caused by a missing login`). Please see if this was the problem.
