### ISSUE TITLE
Blocking issues

### ISSUE THREAD

**Issue by nirshahaf** [boecker-lab/sirius#26]
Hi Sirius team,

After a few weeks of flow-less runs, I started to repeatedly get warnings related to scoring of the fragmentation trees, such as:

> There is a large gap between the optimal solution and the score of the computed fragmentation tree: Gap is 1.3559191947010163E-7 for a score of 55.503432884

...and immediately after:

> FasterTreeComputationInstance (101): ExactJob: Score of C7H26N9O4 differs significantly from recalculated score: 95.49730043266138 vs 88.2112108354583 with tree size is 0.5 and root score is -2.05843558645278 and 0.5 sort key is score 95.49730043266138

..worst, the program started to block and I have to kill the process or close the terminal to stop it - it seems somehow related to the jvm settings and I notice that the program is not using the Swap at all - but riding on the free RAM. When stopping I get:

> java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Object.wait(Unknown Source)
	at java.desktop/sun.awt.AWTAutoShutdown.activateBlockerThread(Unknown Source)
	at java.desktop/sun.awt.AWTAutoShutdown.notifyThreadBusy(Unknown Source)
	at java.desktop/java.awt.EventQueue$6.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$6.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.EventQueue.initDispatchThread(Unknown Source)
	at java.desktop/java.awt.EventQueue.postEventPrivate(Unknown Source)
	at java.desktop/java.awt.EventQueue.postEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.invokeLater(Unknown Source)
	at ca.odell.glazedlists.impl.swing.SwingThreadProxyEventList.schedule(SwingThreadProxyEventList.java:36)
	at ca.odell.glazedlists.impl.gui.ThreadProxyEventList.listChanged(ThreadProxyEventList.java:119)
	at ca.odell.glazedlists.event.ListEventAssembler$ListEventFormat.fire(ListEventAssembler.java:434)
	at ca.odell.glazedlists.event.ListEventAssembler$ListEventFormat.fire(ListEventAssembler.java:430)
	at ca.odell.glazedlists.event.SequenceDependenciesEventPublisher$SubjectAndListener.firePendingEvent(SequenceDependenciesEventPublisher.java:469)
	at ca.odell.glazedlists.event.SequenceDependenciesEventPublisher.fireEvent(SequenceDependenciesEventPublisher.java:365)
	at ca.odell.glazedlists.event.ListEventAssembler.commitEvent(ListEventAssembler.java:326)
	at ca.odell.glazedlists.ObservableElementList.elementChanged(ObservableElementList.java:433)
	at ca.odell.glazedlists.impl.beans.BeanConnector$PropertyChangeHandler.propertyChange(BeanConnector.java:240)
	at java.desktop/java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at de.unijena.bioinf.jjobs.SwingJJobContainer.propertyChange(SwingJJobContainer.java:71)
	at de.unijena.bioinf.jjobs.JJobsPropertyChangeSupport.lambda$fire$1(JJobsPropertyChangeSupport.java:261)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at de.unijena.bioinf.jjobs.JJobsPropertyChangeSupport.fire(JJobsPropertyChangeSupport.java:259)
	at de.unijena.bioinf.jjobs.JJobsPropertyChangeSupport.firePropertyChange(JJobsPropertyChangeSupport.java:252)
	at de.unijena.bioinf.jjobs.BasicJJob.firePropertyChange(BasicJJob.java:269)
	at de.unijena.bioinf.jjobs.BasicJJob.updateProgress(BasicJJob.java:275)
	at de.unijena.bioinf.jjobs.BasicJJob.updateProgress(BasicJJob.java:283)
	at de.unijena.bioinf.jjobs.ProgressJJob.updateProgress(ProgressJJob.java:7)
	at de.unijena.bioinf.jjobs.BasicJJob.doFailHandling(BasicJJob.java:133)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:108)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by kaibioinfo** [comment]
Hi,
the two warnings are not severe. The first one is probably just due to rounding errors, the second one seems to be a bug in the JSON output of the tree (at some point we recalculate all scores of a tree to write them into the JSON file. Sometimes, the recalculated score differs from the score we got from the optimization problem. Although this is a bug, it just means that some score in your JSON output is not correct. The computational results are nevertheless valid).

**Comment by nirshahaf** [comment]
Hi Kai 

Thanks for your reply - however that does not resolve the main issue which is that program gets stuck on this warnings and doesn't successfully conclude the run. I have to force-stop it and with the following files missing in the WS folder:

-  compound_identifications.tsv
-  compound_identifications_adducts.tsv
-  formula_identifications.tsv
-  report.mztab

However, the two following files are already created:

- csi_fingerid.tsv
- csi_fingerid_neg.tsv

It might be related to java or performance settings - but I have explicitly fiddled around with these before this issue started. I have only this shell output (once killed):

> AWT blocker activation interrupted:
java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Object.wait(Unknown Source)
	at java.desktop/sun.awt.AWTAutoShutdown.activateBlockerThread(Unknown Source)
	at java.desktop/sun.awt.AWTAutoShutdown.notifyThreadBusy(Unknown Source)
	at java.desktop/java.awt.EventQueue$6.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$6.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.EventQueue.initDispatchThread(Unknown Source)
	at java.desktop/java.awt.EventQueue.postEventPrivate(Unknown Source)
	at java.desktop/java.awt.EventQueue.postEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.invokeLater(Unknown Source)
	at ca.odell.glazedlists.impl.swing.SwingThreadProxyEventList.schedule(SwingThreadProxyEventList.java:36)
	at ca.odell.glazedlists.impl.gui.ThreadProxyEventList.listChanged(ThreadProxyEventList.java:119)
	at ca.odell.glazedlists.event.ListEventAssembler$ListEventFormat.fire(ListEventAssembler.java:434)
	at ca.odell.glazedlists.event.ListEventAssembler$ListEventFormat.fire(ListEventAssembler.java:430)
	at ca.odell.glazedlists.event.SequenceDependenciesEventPublisher$SubjectAndListener.firePendingEvent(SequenceDependenciesEventPublisher.java:469)
	at ca.odell.glazedlists.event.SequenceDependenciesEventPublisher.fireEvent(SequenceDependenciesEventPublisher.java:365)
	at ca.odell.glazedlists.event.ListEventAssembler.commitEvent(ListEventAssembler.java:326)
	at ca.odell.glazedlists.ObservableElementList.elementChanged(ObservableElementList.java:433)
	at ca.odell.glazedlists.impl.beans.BeanConnector$PropertyChangeHandler.propertyChange(BeanConnector.java:240)
	at java.desktop/java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at de.unijena.bioinf.jjobs.SwingJJobContainer.propertyChange(SwingJJobContainer.java:71)
	at de.unijena.bioinf.jjobs.JJobsPropertyChangeSupport.lambda$fire$1(JJobsPropertyChangeSupport.java:261)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at de.unijena.bioinf.jjobs.JJobsPropertyChangeSupport.fire(JJobsPropertyChangeSupport.java:259)
	at de.unijena.bioinf.jjobs.JJobsPropertyChangeSupport.firePropertyChange(JJobsPropertyChangeSupport.java:252)
	at de.unijena.bioinf.jjobs.BasicJJob.firePropertyChange(BasicJJob.java:269)
	at de.unijena.bioinf.jjobs.BasicJJob.updateProgress(BasicJJob.java:275)
	at de.unijena.bioinf.jjobs.BasicJJob.updateProgress(BasicJJob.java:283)
	at de.unijena.bioinf.jjobs.ProgressJJob.updateProgress(ProgressJJob.java:7)
	at de.unijena.bioinf.jjobs.BasicJJob.doFailHandling(BasicJJob.java:133)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:108)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Any clue?

**Comment by kaibioinfo** [comment]
Right, I just wanted to point out that the two warnings are not related to the deadlock. From the log it seems like you use the GUI? When the GUI is not responsive anymore, this could indeed some out-of-memory problem. 
Its still quite likely that the projectspace is intact. If you restart the program, it should recompute all the summary files which are missing.

**Comment by nirshahaf** [comment]
Actually, I'm calling the command line tool - and just to make sure, have downloaded the recent release 'sirius-4.6.1-linux64-headless' and run it again with the same conditions w/wo the 'structure' tag - however it keeps getting stuck after writing all the directories for the individual spectra (however without the 'formula_candidates.tsv' files - and in general not writing the overall project output files). Additionally I tried an older release (4.5.2) and reducing the number of available cores to prevent resource overload - however none resolves the issue. I therefore conclude that it must be some implicit change in the local Linux environment - possibly the Java definitions. Do you perhaps have any general advise in this case?

**Comment by nirshahaf** [comment]
Kai, Markus,

Thanks for adding the comprehensive logging option to Sirius. The process keeps hanging at this point:

> FINE  08:41:30 - TreeComputationJob (81104): Running cleanup
FINE  08:41:30 - TreeComputationJob (81105): Running post processing
FINE  08:41:30 - TreeComputationJob (81105): Running cleanup
FINE  08:41:30 - TreeComputationJob (21235): Running post processing
FINE  08:41:30 - TreeComputationJob (21235): Running cleanup
FINE  08:41:30 - TreeComputationJob (21246): Running post processing
FINE  08:41:30 - TreeComputationJob (21246): Running cleanup

Any idea why?

Can I ask you at this point which processes are completely autonomous and which depend on your server?
I am trying to understand if some change on your server can cause this sudden change in software activity.

Thanks!

**Comment by rickhelmus** [comment]
Seems to be facing the same issue here. I think it started in the past few days. Summary:
* Tried different versions: 4.7.4, 4.8.1, 4.8.2
* Tried going through VPN to see if it's network related
* Removed `~/.siriusX` folders
* Tried Linux and Windows

The formula calculation (exact same data) works fine, so I guess it hangs on CSI:FingerID?

**Comment by mfleisch** [comment]
Hey, are you parallelizing your workloads inside SIRIUS or are you running many instances of SIRIUS at the same time?

The client itself uses a fixed number of connections independently from the number of cores used for computation. So this should scale well to hundreds of cores.
But if you run a large number of SIRIUS processes at the same time it could indeed be that the web server runs out of connections at some point.

**Comment by rickhelmus** [comment]
Hi Markus,

The parallellizing is done by SIRIUS. 

I just did a small query again (n=8) and all seems fine. I hope it was just a server issue, but will check if I can get more details if it happens again.

**Comment by mfleisch** [comment]
There might be a relation to #43 which was fixed in 4.9.0.
I'm Closing the issue, Feel free reopen if the problem persists.

**Comment by nirshahaf** [comment]
Hi,

Actually, I think that the performance problem at issue #43 was discussed
between us already some monts ago in relation to high mass natural
products. I resolved it here by adaptively setting some run parameters
according to the input mass.

My "blocking issue" was most probably related to communication with the CSI
server - and to my surprise, I tried the CLI again today with the same
calls on the same PC and both CSI and Canopus seem to be working just fine!
I could not dereplicate
the issue so far - so my assumption is that something must have changed on
the server side.

Now the problem is that I have many Sirius project directories, without the
structure predictions (but all 'formula' calculations were done) - can I
re-use these results to predict structures without having to recompute all
the fragmentation trees? (using the CLI)

Thanks
Nir

**Comment by mfleisch** [comment]
Hey,
yes you can do that. Just use the project-space as an input like this:

`sirius -i <project-with-results> sirius fingerid canopus`

Unless you are not setting the `--recompute`  parameter SIRIUS will skip computing steps for which results are already available. If you are sure that formula calculations are already
done for **all** instances you can entirely save the `sirius` step like this:

`sirius -i <project-with-results> fingerid canopus`

**Comment by nirshahaf** [comment]
Hi,

The second option works nicely! But now I have two main doubts with the
computations of fragmentation trees:

(1) In some cases Sirius doesn't seem to consider well the adducts (I did
opened an issue regarding [M]+ adduct CF computation some weeks ago), but
also this, in the NI mode with the formic acid adduct, doesn't seem right:

mz intensity rel.intensity exactmass formula ionization implicitAdduct
911.499147 588.01 100 865.495495 C46H74O15 [M - H]- CH2O2 Fragments are
most probably not FA adducts and CF is wrong! (plus isotopes not
filtered-out)
912.502626 265.86 45.21 866.50332 C46H75O15 [M - H]- CH2O2
913.513164 99.55 16.93 867.511145 C46H76O15 [M - H]- CH2O2
1415.567452 0 0 1369.555374 C61H94O34 [M - H]- CH2O2 ←parent is an FA adduct

Is it an issue with properly setting one of the "adduct" config parameters?
But which one of them: "PossibleAdductSwitches",
"AdductSettings.detectable" or "AdductSettings.fallback" ?

(2) The "--IsotopeMs2Settings=SCORE or FILTER" do not seem to affect the
result and the trees are infiltrated with isotopes detected wrongly as
fragments (V 4.6.1 and 4.8.2)...

Thanks again,
Nir

**Comment by nirshahaf** [comment]
Hi,

I'm sorry for repeating myself, but the CLI is again hanging while
communicating with the 'fingerid' server for no obvious reason (same files,
same PC - worked smoothly about two weeks ago...)
In contrast, the Sirius GUI is working perfectly OK and giving both
FingerID and Canopus results for the same project. Below is the CLI output:


> INFO  18:21:57 - Sirius Workspace Successfull initialized at:
> /home/metaboaa01/.sirius-4.6/csi_fingerid_cache/custom
> INFO  18:21:57 - You run SIRIUS 4.6.1
> INFO  18:21:57 - Sirius was compiled with the following ILP solvers:
> GLPK-v1.7.0 (included), Gurobi-v8.1.0, CPLEX-v12.7.1, COIN-OR-v1.17.3
> INFO  18:21:57 - Treebuilder priorities are: [CLP, CPLEX, GUROBI, GLPK]
> INFO  18:21:57 - CPU check done. 16 cores that handle 32 threads were
> found.
> INFO  18:21:57 - Bug reporter initialized.
> INFO  18:21:57 - Web API initialized.
> INFO  18:21:57 - Running with following arguments: [-i, Sirius/001/,
> --cores=1, structure, --database=ALL_BUT_INSILICO, canopus]
> INFO  18:21:57 - Job manager successful initialized with 16 CPU thread(s)
> and 3 IO thread(s).
> FINE  18:21:57 - InputExpanderJJob (0): Running post processing
> FINE  18:21:57 - InputExpanderJJob (0): Running cleanup
> INFO  18:21:57 - InputExpanderJJob (1): Expanding Input Files:
> 'Sirius/001'...
> INFO  18:21:57 - InputExpanderJJob (1): ...Input Files successfully
> expanded!
> FINE  18:21:57 - InputExpanderJJob (1): Running post processing
> FINE  18:21:57 - InputExpanderJJob (1): Running cleanup
> INFO  18:21:57 - Shutting down JobManager
> INFO  18:21:57 - Awaiting termination of JobManager
> INFO  18:21:57 - JobManager is shut down
> INFO  18:21:58 - No output location given. Writing output to input
> location: Sirius/001
> WARNING18:21:58 - target location 'Sirius/001' was also part of the INPUT
> and will be ignored!
> SEVERE18:22:00 - Error when loading confidence SVMs or the bayesian
> network. Confidence SCore will not be available
>

...from here on it got stuck and I stopped it after ~10 min. (the same
process has completed within seconds about two weeks ago).

Thanks!
Nir

**Comment by nirshahaf** [comment]
*Update:

Running with CLI version 4.8.2 (instead of 4.6.1) is working fine. Will
update if anything goes wrong again.

Nir
