### ISSUE TITLE
X11 DISPLAY error on remote linux server

### ISSUE THREAD

**Issue by louwenjjr** [boecker-lab/sirius#35]
I am running the sirius command line tool (SIRIUS 4.7.4) from a remote linux server. I am using a folder of mzXML files as input. When running the following command:
```
sirius -i test_spec/ -o sirius_test_spec --maxmz=600 lcms-align sirius zodiac fingerid canopus
```
I get this error:
```
SEVERE  00:12:17 - Unexpected Error!
java.lang.ExceptionInInitializerError
        at de.unijena.bioinf.projectspace.GuiProjectSpaceManager.<init>(GuiProjectSpaceManager.java:80)
        at de.unijena.bioinf.projectspace.GuiProjectSpaceManagerFactory.create(GuiProjectSpaceManagerFactory.java:39)
        at de.unijena.bioinf.projectspace.GuiProjectSpaceManagerFactory.create(GuiProjectSpaceManagerFactory.java:35)
        at de.unijena.bioinf.projectspace.GuiProjectSpaceManagerFactory.create(GuiProjectSpaceManagerFactory.java:31)
        at de.unijena.bioinf.projectspace.ProjectSpaceManagerFactory.create(ProjectSpaceManagerFactory.java:35)
        at de.unijena.bioinf.ms.frontend.subtools.CLIRootOptions.configureProjectSpace(CLIRootOptions.java:183)
        at de.unijena.bioinf.ms.frontend.subtools.CLIRootOptions.getProjectSpace(CLIRootOptions.java:147)
        at de.unijena.bioinf.ms.frontend.subtools.lcms_align.LcmsAlignSubToolJob.<init>(LcmsAlignSubToolJob.java:60)
        at de.unijena.bioinf.ms.frontend.subtools.lcms_align.LcmsAlignOptions.makePreprocessingJob(LcmsAlignOptions.java:33)
        at de.unijena.bioinf.ms.frontend.subtools.lcms_align.LcmsAlignOptions.makePreprocessingJob(LcmsAlignOptions.java:28)
        at de.unijena.bioinf.ms.frontend.workflow.WorkflowBuilder$ParseResultHandler.handle(WorkflowBuilder.java:210)
        at de.unijena.bioinf.ms.frontend.workflow.WorkflowBuilder$ParseResultHandler.handle(WorkflowBuilder.java:190)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2073)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:2454)
        at picocli.CommandLine.parseWithHandler(CommandLine.java:2389)
        at de.unijena.bioinf.ms.frontend.Run.parseArgs(Run.java:75)
        at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.run(SiriusCLIApplication.java:109)
        at de.unijena.bioinf.ms.frontend.SiriusGUIApplication$1.compute(SiriusGUIApplication.java:84)
        at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:120)
        at de.unijena.bioinf.ms.frontend.SiriusGUIApplication.main(SiriusGUIApplication.java:98)
Caused by: java.awt.HeadlessException:
No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(Unknown Source)
        at java.desktop/java.awt.Window.<init>(Unknown Source)
        at java.desktop/java.awt.Frame.<init>(Unknown Source)
        at java.desktop/javax.swing.JFrame.<init>(Unknown Source)
        at de.unijena.bioinf.ms.gui.mainframe.MainFrame.<init>(MainFrame.java:139)
        at de.unijena.bioinf.ms.gui.mainframe.MainFrame.<clinit>(MainFrame.java:63)
        ... 20 more
```
When running the same command from my local windows machine with the windows version (SIRIUS 4.7.4) it does work. I tried setting my DISPLAY value to listen to my local machine but this didn't help.

Any idea what is going wrong here? Maybe some setting on my remote server that is not configured properly?

**Comment by mfleisch** [comment]
Hey,
are you using the "Command-Line Interface only" (headless) version of SIRIUS on the remote server or the one that also includes the GUI? For servers the "Command-Line Interface only" (headless) version is needed.

**Comment by louwenjjr** [comment]
Ah yes indeed that was the issue. I must have missed that in the docs. Thanks for the quick reply!
