### ISSUE TITLE
Under win10, sirius can run normally, but after upgrading to Win11, sirius cannot run normally

### ISSUE THREAD

**Issue by linkai1208** [boecker-lab/sirius#53]
Under win10, sirius can run normally, but after upgrading to Win11, sirius cannot run normally.
Can you tell me the reason? 
thanks！
==========================================
INFO    17:29:45 - Sirius Workspace Successfull initialized at: C:\Users\SLG\.sirius-4.9
INFO    17:29:45 - You run SIRIUS 4.9.9
INFO    17:29:45 - Sirius was compiled with the following ILP solvers: GLPK-v1.7.0 (included), Gurobi-v9.1.1, CPLEX-v12.7.1, COIN-OR-v1.17.3
INFO    17:29:45 - Treebuilder priorities loaded from 'sirius.properties' are: [GUROBI, CPLEX, CLP, GLPK]
Application Core STATIC Block Error!
java.lang.IllegalStateException: Unmapped relationship: 7
        at com.sun.jna.platform.win32.WinNT$SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX.fromPointer(WinNT.java:3033)
        at com.sun.jna.platform.win32.Kernel32Util.getLogicalProcessorInformationEx(Kernel32Util.java:715)
        at oshi.driver.windows.LogicalProcessorInformation.getLogicalProcessorInformationEx(LogicalProcessorInformation.java:61)
        at oshi.hardware.platform.windows.WindowsCentralProcessor.initProcessorCounts(WindowsCentralProcessor.java:149)
        at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:73)
        at oshi.hardware.platform.windows.WindowsCentralProcessor.<init>(WindowsCentralProcessor.java:68)
        at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.createProcessor(WindowsHardwareAbstractionLayer.java:60)
        at oshi.util.Memoizer$1.get(Memoizer.java:87)
        at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:66)
        at de.unijena.bioinf.ms.frontend.core.ApplicationCore.<clinit>(ApplicationCore.java:285)
        at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.run(SiriusCLIApplication.java:108)
        at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.main(SiriusCLIApplication.java:53)
        at de.unijena.bioinf.ms.frontend.SiriusGUIApplication.main(SiriusGUIApplication.java:56)
SEVERE  17:29:45 - Unexpected Error!
java.lang.ExceptionInInitializerError
        at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.run(SiriusCLIApplication.java:108)
        at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.main(SiriusCLIApplication.java:53)
        at de.unijena.bioinf.ms.frontend.SiriusGUIApplication.main(SiriusGUIApplication.java:56)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Unmapped relationship: 7
        at de.unijena.bioinf.ms.frontend.core.ApplicationCore.<clinit>(ApplicationCore.java:305)
        ... 3 more
Caused by: java.lang.IllegalStateException: Unmapped relationship: 7
        at com.sun.jna.platform.win32.WinNT$SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX.fromPointer(WinNT.java:3033)
        at com.sun.jna.platform.win32.Kernel32Util.getLogicalProcessorInformationEx(Kernel32Util.java:715)
        at oshi.driver.windows.LogicalProcessorInformation.getLogicalProcessorInformationEx(LogicalProcessorInformation.java:61)
        at oshi.hardware.platform.windows.WindowsCentralProcessor.initProcessorCounts(WindowsCentralProcessor.java:149)
        at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:73)
        at oshi.hardware.platform.windows.WindowsCentralProcessor.<init>(WindowsCentralProcessor.java:68)
        at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.createProcessor(WindowsHardwareAbstractionLayer.java:60)
        at oshi.util.Memoizer$1.get(Memoizer.java:87)
        at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:66)
        at de.unijena.bioinf.ms.frontend.core.ApplicationCore.<clinit>(ApplicationCore.java:285)
        ... 3 more

**Comment by mfleisch** [comment]
Hey,
thanks for the report. We currently have no Windows 11 infrastructure available for detailed testing but are working on it.

However, I deployed a pre-release version that  might fix your problem. Can you please try if the the following version is working.
https://github.com/boecker-lab/sirius/releases/tag/v4.9.11-SNAPSHOT

**Comment by mfleisch** [comment]
FYI: you can also use the new 4.9.12 release for testing.
