### ISSUE TITLE
Unexpected error : java.lang.NullPointerException: Cannot invoke "de.unijena.bioinf.ms.gui.net.ConnectionMonitor$ConnetionCheck.isConnected()" 

### ISSUE THREAD

**Issue by simmlerc** [boecker-lab/sirius#59]
Hi Sirius Team,

SIRIUS-gui, I installed was working fine on my PC (windows 10, 64 bit), and I have the latest Java 8 version installed as well. But these last two days, on opening the SIRIUS.GUI I received this message: 

Unexpected error!
java.lang.NullPointerException: Cannot invoke "de.unijena.bioinf.ms.gui.net.ConnectionMonitor$ConnetionCheck.isConnected()" because "cc" is null
	at de.unijena.bioinf.ms.frontend.subtools.gui.GuiAppOptions$Flow$2.compute(GuiAppOptions.java:152)
	at de.unijena.bioinf.ms.frontend.subtools.gui.GuiAppOptions$Flow$2.compute(GuiAppOptions.java:128)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:120)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Have you ever received this type of error message before?

Thanks for your advice and help,

Regards,
Charlotte

**Comment by mfleisch** [comment]
Hey Charlotte,
Have you already tried the latest release? Please let me know If the error persists with the latest release.
