### ISSUE TITLE
Running sirius failed even with the demo_data

### ISSUE THREAD

**Issue by YUANMY2021** [boecker-lab/sirius#62]
### 01. The Command 
sirius -i ../ipo_xcms_noise1000_neg_maxtic.mgf -o ./output328/ formula -c 10 structure --database pubchem

### 02. The running log 
Mar 28, 2022 2:27:09 PM de.unijena.bioinf.jjobs.JJob logInfo
INFO:  (0): Starting Application Core...
INFO  14:27:10 - Sirius Workspace Successfull initialized at: /share/home/jianglab/yuanmengyi/.sirius-4.6
INFO  14:27:10 - You run SIRIUS 4.6.1
INFO  14:27:10 - Sirius was compiled with the following ILP solvers: GLPK-v1.7.0 (included), Gurobi-v8.1.0, CPLEX-v12.7.1, COIN-OR-v1.17.3
INFO  14:27:10 - Treebuilder priorities are: [CLP, CPLEX, GUROBI, GLPK]
INFO  14:27:10 - CPU check done. 32 cores that handle 64 threads were found.
INFO  14:27:10 - Bug reporter initialized.
INFO  14:27:10 - Web API initialized.
INFO  14:27:10 - Starting Application Core
INFO  14:27:10 - Job manager successful initialized with 32 CPU thread(s) and 1 IO thread(s).
INFO  14:27:10 - Swing Job MANAGER initialized! 32 : 1
INFO  14:27:10 -  (0): Configure shutdown hooks...
INFO  14:27:10 -  (0): Configure Workflows... 
INFO  14:27:10 -  (0): Firing up SIRIUS... 
INFO  14:27:11 - Running with following arguments: [-i, ../ipo_xcms_noise1000_neg_maxtic.mgf, -o, ./output328/, formula, -c, 10, structure, --database, pubchem]
FINE  14:27:11 - InputExpanderJJob (1): Running post processing
FINE  14:27:11 - InputExpanderJJob (1): Running cleanup
INFO  14:27:11 - InputExpanderJJob (2): Expanding Input Files: '../ipo_xcms_noise1000_neg_maxtic.mgf'...
INFO  14:27:11 - InputExpanderJJob (2): ...Input Files successfully expanded!
FINE  14:27:11 - InputExpanderJJob (2): Running post processing
FINE  14:27:11 - InputExpanderJJob (2): Running cleanup
SEVERE14:27:11 -  (3): Failed!
java.io.IOException: Location './output328' is not a valid Project Location
	at de.unijena.bioinf.projectspace.ProjectSpaceIO.openExistingProjectSpace(ProjectSpaceIO.java:56)
	at de.unijena.bioinf.ms.frontend.subtools.CLIRootOptions.configureProjectSpace(CLIRootOptions.java:161)
	at de.unijena.bioinf.ms.frontend.subtools.CLIRootOptions.getProjectSpace(CLIRootOptions.java:140)
	at de.unijena.bioinf.ms.frontend.subtools.CLIRootOptions$1.compute(CLIRootOptions.java:225)
	at de.unijena.bioinf.ms.frontend.subtools.CLIRootOptions$1.compute(CLIRootOptions.java:222)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:95)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

SEVERE14:27:11 - Error When Executing ToolChain
java.util.concurrent.ExecutionException: java.io.IOException: Location './output328' is not a valid Project Location
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at de.unijena.bioinf.jjobs.BasicJJob.awaitResult(BasicJJob.java:175)
	at de.unijena.bioinf.ms.frontend.workflow.ToolChainWorkflow.run(ToolChainWorkflow.java:84)
	at de.unijena.bioinf.ms.frontend.Run.compute(Run.java:60)
	at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.run(SiriusCLIApplication.java:113)
	at de.unijena.bioinf.ms.frontend.SiriusGUIApplication$1.compute(SiriusGUIApplication.java:84)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:95)
	at de.unijena.bioinf.ms.frontend.SiriusGUIApplication.main(SiriusGUIApplication.java:98)
Caused by: java.io.IOException: Location './output328' is not a valid Project Location
	at de.unijena.bioinf.projectspace.ProjectSpaceIO.openExistingProjectSpace(ProjectSpaceIO.java:56)
	at de.unijena.bioinf.ms.frontend.subtools.CLIRootOptions.configureProjectSpace(CLIRootOptions.java:161)
	at de.unijena.bioinf.ms.frontend.subtools.CLIRootOptions.getProjectSpace(CLIRootOptions.java:140)
	at de.unijena.bioinf.ms.frontend.subtools.CLIRootOptions$1.compute(CLIRootOptions.java:225)
	at de.unijena.bioinf.ms.frontend.subtools.CLIRootOptions$1.compute(CLIRootOptions.java:222)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:95)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

INFO  14:27:11 - CLI shut down hook: SIRIUS is cleaning up threads and shuts down...

Please cite the following publications when using our tool:

When using the SIRIUS Software please cite the following paper:

Kai D?hrkop, Markus Fleischauer, Marcus Ludwig, Alexander A. Aksenov, Alexey V. Melnik, Marvin Meusel, Pieter C. Dorrestein, Juho Rousu and Sebastian B?cker
SIRIUS4: a rapid tool for turning tandem mass spectra into metabolite structure information
Nat Methods, 16, 2019.  https://doi.org/10.1038/s41592-019-0344-8

Depending on the tools you have used please also cite:

Kai D?hrkop, Louis-F?lix Nothias, Markus Fleischauer, Raphael Reher, Marcus Ludwig, Martin A. Hoffmann, Daniel Petras, William H. Gerwick, Juho Rousu, Pieter C. Dorrestein and Sebastian B?cker
Systematic classification of unknown metabolites using high-resolution fragmentation mass spectra
Nature Biotechnology, 2020.  https://doi.org/10.1038/s41587-020-0740-8
(Cite if you are using: CANOPUS)

Yannick Djoumbou Feunang, Roman Eisner, Craig Knox, Leonid Chepelev, Janna Hastings, Gareth Owen, Eoin Fahy, Christoph Steinbeck, Shankar Subramanian, Evan Bolton, Russell Greiner, David S. Wishart
ClassyFire: automated chemical classification with a comprehensive, computable taxonomy
J Cheminf, 8, 2016.  https://doi.org/10.1186/s13321-016-0174-y
(Cite if you are using: CANOPUS)

Kai D?hrkop, Huibin Shen, Marvin Meusel, Juho Rousu and Sebastian B?cker
Searching molecular structure databases with tandem mass spectra using CSI:FingerID
Proc Natl Acad Sci U S A, 112, 2015.  https://doi.org/10.1073/pnas.1509788112
(Cite if you are using: CSI:FingerID)

Sebastian B?cker and Kai D?hrkop
Fragmentation trees reloaded
J Cheminform, 8, 2016.  https://doi.org/10.1186/s13321-016-0116-8
(Cite if you are using: Fragmentation Trees)

Sebastian B?cker, Matthias Letzel, Zsuzsanna Lipt?k and Anton Pervukhin
SIRIUS: Decomposing isotope patterns for metabolite identification
Bioinformatics, 25, 2009.  https://doi.org/10.1093/bioinformatics/btn603
(Cite if you are using: Isotope Pattern analysis)

Marcus Ludwig, Louis-F?lix Nothias, Kai D?hrkop, Irina Koester, Markus Fleischauer, Martin A. Hoffmann, Daniel Petras, Fernando Vargas, Mustafa Morsy, Lihini Aluwihare, Pieter C. Dorrestein, Sebastian B?cker
ZODIAC: database-independent molecular formula annotation using Gibbs sampling reveals unknown small molecules
bioRxiv, 2019.  https://doi.org/10.1101/842740
(Cite if you are using: ZODIAC)

**Comment by mfleisch** [comment]
Could it be, that the directory `./output328/` is already existing (an presumably empty)?
If yes please delete the directory before writing into this location, since the directory where the new project-space is to be created must not exist.

**Comment by YUANMY2021** [comment]
Thanks for replying me💕, but the main problem may not be that ?🤔

Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set

<img width="944" alt="image" src="https://user-images.githubusercontent.com/79961133/160518664-aef63f5e-950c-4cfd-9dcd-d66a2e32e8f1.png">

**Comment by mfleisch** [comment]
Hey,
yes the not valid project-space error is likely to be a consequential error of the  ''Headless Exception" you reported recently.
What likely happened is the following:
1. You run sirius the first time on som output directory, it crashed during the creation of the project-space and leaves an empty directory on the system.
2. Then the directory does already exist when trying the command a second time.
-----
**Regarding the ''Headless Exception"**
1. I am assuming you are on a linux server without display server (console only). 
2. You should switch to the headless (command line only) version of SIRIUS. It is especially build for server environments and does not contain libraries that depend on a display server.
3. You are using version 4.6. which is already quite old. We changed the GUI version of SIRIUS in some later version to work in "command line only" environments unless you are not trying to start the GUI. So upgrading to the latest version (4.9.15) should also fix the ''Headless Exception" problem.

**Comment by YUANMY2021** [comment]
Thanks for replying me, I will try now

**Comment by YUANMY2021** [comment]
I use the 4.9.12 and successfully running! Thanks!!
