### ISSUE TITLE
argument "src" is null

### ISSUE THREAD

**Issue by SarahLenn** [boecker-lab/sirius#85]
Dear all,

I am using Sirius via the GUI. I am currently running into an issue. I am trying to create a custom database from a list of smiles. I get the error below.
I have tried to uninstall and reinstall Sirius without much success.
Would you have any suggestion ?

Thank you very much for your help,
Kind regards,
Sarah Lennon

Oct 03, 2022 9:51:45 AM de.unijena.bioinf.ms.frontend.subtools.custom_db.CustomDBOptions$CustomDBWorkflow run
GRAVE: error when storing custom db
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: argument "src" is null
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at de.unijena.bioinf.jjobs.BasicJJob.awaitResult(BasicJJob.java:205)
	at de.unijena.bioinf.ms.frontend.subtools.custom_db.CustomDBOptions$CustomDBWorkflow.run(CustomDBOptions.java:102)
	at de.unijena.bioinf.ms.gui.compute.jjobs.Jobs$ComputationJJob.compute(Jobs.java:261)
	at de.unijena.bioinf.ms.gui.compute.jjobs.Jobs$ComputationJJob.compute(Jobs.java:231)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:117)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: argument "src" is null
	at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4829)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3673)
	at de.unijena.bioinf.storage.blob.file.FileBlobStorage.lambda$getTags$2(FileBlobStorage.java:88)
	at de.unijena.bioinf.storage.blob.file.FileBlobStorage.withWriteLock(FileBlobStorage.java:228)
	at de.unijena.bioinf.storage.blob.file.FileBlobStorage.getTags(FileBlobStorage.java:86)
	at de.unijena.bioinf.storage.blob.CompressibleBlobStorage.of(CompressibleBlobStorage.java:40)
	at de.unijena.bioinf.chemdb.custom.CustomDatabase.open(CustomDatabase.java:99)
	at de.unijena.bioinf.chemdb.custom.CustomDatabase.createOrOpen(CustomDatabase.java:107)
	at de.unijena.bioinf.ms.frontend.subtools.custom_db.CustomDBOptions$CustomDBWorkflow.compute(CustomDBOptions.java:130)
	at de.unijena.bioinf.ms.frontend.subtools.custom_db.CustomDBOptions$CustomDBWorkflow.compute(CustomDBOptions.java:90)
	... 5 more

Oct 03, 2022 9:51:45 AM de.unijena.bioinf.ms.frontend.subtools.custom_db.CustomDBOptions$CustomDBWorkflow run
GRAVE: error when storing custom db
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: argument "src" is null
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at de.unijena.bioinf.jjobs.BasicJJob.awaitResult(BasicJJob.java:205)
	at de.unijena.bioinf.ms.frontend.subtools.custom_db.CustomDBOptions$CustomDBWorkflow.run(CustomDBOptions.java:102)
	at de.unijena.bioinf.ms.gui.compute.jjobs.Jobs$ComputationJJob.compute(Jobs.java:261)
	at de.unijena.bioinf.ms.gui.compute.jjobs.Jobs$ComputationJJob.compute(Jobs.java:231)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:117)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: argument "src" is null
	at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4829)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3673)
	at de.unijena.bioinf.storage.blob.file.FileBlobStorage.lambda$getTags$2(FileBlobStorage.java:88)
	at de.unijena.bioinf.storage.blob.file.FileBlobStorage.withWriteLock(FileBlobStorage.java:228)
	at de.unijena.bioinf.storage.blob.file.FileBlobStorage.getTags(FileBlobStorage.java:86)
	at de.unijena.bioinf.storage.blob.CompressibleBlobStorage.of(CompressibleBlobStorage.java:40)
	at de.unijena.bioinf.chemdb.custom.CustomDatabase.open(CustomDatabase.java:99)
	at de.unijena.bioinf.chemdb.custom.CustomDatabase.createOrOpen(CustomDatabase.java:107)
	at de.unijena.bioinf.ms.frontend.subtools.custom_db.CustomDBOptions$CustomDBWorkflow.compute(CustomDBOptions.java:130)
	at de.unijena.bioinf.ms.frontend.subtools.custom_db.CustomDBOptions$CustomDBWorkflow.compute(CustomDBOptions.java:90)
	... 5 more

Oct 03, 2022 9:51:45 AM de.unijena.bioinf.chemdb.SearchableDatabases getCustomDatabaseByPath
GRAVE: argument "src" is null
Oct 03, 2022 9:51:45 AM de.unijena.bioinf.chemdb.SearchableDatabases getCustomDatabaseByPath
GRAVE: argument "src" is null

**Comment by mfleisch** [comment]
Hey Sarah,
which version of SIRIUS are your using? Can you please describe how exactly you have tried to create the custom-db?

Best 
Markus

**Comment by SarahLenn** [comment]
Hi Markus,

Thank you for your answer ! I am using Sirius 5.5.7. 
I think I have got an idea how I made this happened, but I am not sure how to fix it. I created a database using a list of smiles and a location on one of our server. I did not realise Sirius was going to import all the .json file here. So I stopped the process and decided to change the location from the server to local on my laptop and I deleted what Sirius has been imported by Sirius. Since then, I am not able to create a custom DB anymore and I get that argument "src" is null.
I have also tried to install Sirius on another computer, I still have the same issue. I might have corrupted something related to my account. Is this possible ?

Thank you !
Kind regards,
Sarah

**Comment by mfleisch** [comment]
Hey Sarah,
the import process for custom databases will be improved with the upcoming release, including better checks of the location.

The location for the custom db must either:
- be a valid db directory (existing db)
- an empty directory
- not exist

To fix your problem please try deleting the `.sirius-5.5` directory in your user home directory.
This should remove the faulty configuration that is likely to be the reason for this problem.

Best
Markus
