### ISSUE TITLE
Crash by NullPointerException, version  5.5.7

### ISSUE THREAD

**Issue by mapio** [boecker-lab/sirius#88]
Running the CLI version 5.5.7 on GNU/Linux with a moderately large file (but small masses, less than 850) I encounter the following error 

    java.lang.NullPointerException: Cannot invoke "de.unijena.bioinf.ChemistryBase.ms.ft.FTree.getTreeWeight()" because "solve.tree" is null
	    at de.unijena.bioinf.FragmentationTreeConstruction.computation.FasterTreeComputationInstance.recalibrate(FasterTreeComputationInstance.java:577)
	    at de.unijena.bioinf.FragmentationTreeConstruction.computation.FasterTreeComputationInstance$RecalibrationJob.compute(FasterTreeComputationInstance.java:545)
	    at de.unijena.bioinf.FragmentationTreeConstruction.computation.FasterTreeComputationInstance$RecalibrationJob.compute(FasterTreeComputationInstance.java:531)
	    at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:117)
	    at de.unijena.bioinf.jjobs.BasicMasterJJob$1.compute(BasicMasterJJob.java:101)
	    at java.base/java.util.concurrent.RecursiveTask.exec(Unknown Source)
	    at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	    at java.base/java.util.concurrent.ForkJoinTask.awaitDone(Unknown Source)
	    at java.base/java.util.concurrent.ForkJoinTask.join(Unknown Source)
	    at de.unijena.bioinf.jjobs.BasicJJob.awaitResult(BasicJJob.java:205)
	    at de.unijena.bioinf.jjobs.JJob.takeResult(JJob.java:248)
	    at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	    at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	    at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	    at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	    at de.unijena.bioinf.FragmentationTreeConstruction.computation.FasterTreeComputationInstance.estimateTreeSizeAndRecalibration(FasterTreeComputationInstance.java:304)
	    at de.unijena.bioinf.FragmentationTreeConstruction.computation.FasterTreeComputationInstance.compute(FasterTreeComputationInstance.java:173)
	    at de.unijena.bioinf.FragmentationTreeConstruction.computation.FasterTreeComputationInstance.compute(FasterTreeComputationInstance.java:55)
	    at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:117)
	    at de.unijena.bioinf.jjobs.BasicMasterJJob$1.compute(BasicMasterJJob.java:101)
	    at java.base/java.util.concurrent.RecursiveTask.exec(Unknown Source)
	    at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	    at java.base/java.util.concurrent.ForkJoinTask.awaitDone(Unknown Source)
	    at java.base/java.util.concurrent.ForkJoinTask.join(Unknown Source)
	    at de.unijena.bioinf.jjobs.BasicJJob.awaitResult(BasicJJob.java:205)
	    at de.unijena.bioinf.sirius.Sirius$SiriusIdentificationJob.compute(Sirius.java:631)
	    at de.unijena.bioinf.sirius.Sirius$SiriusIdentificationJob.compute(Sirius.java:614)
	    at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:117)
	    at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
	    at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	    at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	    at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

that seems related to #48.

Any clues on why this happens?

**Comment by mfleisch** [comment]
Hey,
ist this issue reproducible. So does it happen every time when are analyzing this file?
If yes could you share the file?

Best
Markus

**Comment by mapio** [comment]
Dear @mfleisch are there any news?

**Comment by mfleisch** [comment]
Hey,
I will be able to look into this at the end of this week.

**Comment by marcus-ludwig** [comment]
Hi, I believe we fixed this. The real issues in the background occurred when scoring isotopes in MS2 for M+Na compounds. The NullPointer is just a result of this, but is also fixed now.

**Comment by mapio** [comment]
I've downloaded the latest release (5.6.3) and I still can reproduce the error under the same conditions of the original report :(

You plan to include the fix you mention in the closing message in a future release, or you expected it to be already in 5.6.3?

In this case, can you please confirm that the bug persists (with the same input file) and reopen the bug?

**Comment by marcus-ludwig** [comment]
Sorry, I didn't specify: I fixed this yesterday and it is now in our pre-release version 5.6.4-SNAPSHOT.
https://github.com/boecker-lab/sirius/releases/tag/v5.6.4-SNAPSHOT

**Comment by mapio** [comment]
I confirm that, at least on the data cited in this bug-report, the issue seems to be solved. Thanks a lot!
