### ISSUE TITLE
some problems with the network service

### ISSUE THREAD

**Issue by kuntuse** [boecker-lab/sirius#97]
hey,
I am having network connection problems during login in the CLI. It seems that version information counld not be loaded. I re-downloaded the zip and reinstalled it, but it still doesn't work.

sirius login -u xupeng126@zju.edu.cn -p
Jan 13, 2023 4:54:28 PM org.apache.commons.beanutils.FluentPropertyBeanIntrospector introspect
INFO: Error when creating PropertyDescriptor for public final void org.apache.commons.configuration2.AbstractConfiguration.setProperty(java.lang.String,java.lang.Object)! Ignoring this property.
INFO    16:54:29 - Sirius Workspace Successfull initialized at: /home/XP/.sirius-5.6
INFO    16:54:29 - You run SIRIUS 5.6.3
INFO    16:54:29 - You run SIRIUS in 'CLI' mode.
INFO    16:54:29 - Sirius was compiled with the following ILP solvers: GLPK-v1.7.0 (included), Gurobi-v9.1.1, CPLEX-v12.7.1, COIN-OR-v1.17.3
INFO    16:54:29 - Treebuilder priorities loaded from 'sirius.properties' are: [CLP, GUROBI, CPLEX]
INFO    16:54:29 - CPU check done. 52 cores that handle 104 threads were found.
INFO    16:54:32 - Web API initialized.
INFO    16:54:32 - Running with following arguments: [login, -u, xupeng126@zju.edu.cn, -p]
Enter value for --password (Console password input.): 
INFO    16:54:41 - Job manager successful initialized with 84 CPU thread(s) and 4 IO thread(s).
INFO    16:54:42 - Starting http Client with MaxPerRout=4 / maxTotal=5(Threads=84).
WARNING 16:54:43 - Could not reach secured api endpoint. Bad Response Code. Cause: Error when querying REST service. Bad Response Code: 404 | Message: Not Found | Content: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

WARNING 16:54:45 - Could not load version info (unsecured api endpoint). Bad Response Code. Cause: Error when querying REST service. Bad Response Code: 404 | Message: Not Found | Content: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

WARNING 16:55:08 - Connection error
org.apache.hc.client5.http.ConnectTimeoutException: Connect to https://www.google.com:443 [www.google.com/50.117.117.42, www.google.com/2001:0:0:0:0:0:a88f:a234] failed: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory$1.run(SSLConnectionSocketFactory.java:219)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:216)
	at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:148)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:396)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:158)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:168)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:136)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:175)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:75)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:89)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:54)
	at de.unijena.bioinf.rest.ProxyManager.checkConnectionToUrl(ProxyManager.java:373)
	at de.unijena.bioinf.rest.ProxyManager.checkExternal(ProxyManager.java:350)
	at de.unijena.bioinf.rest.ProxyManager.checkInternetConnection(ProxyManager.java:171)
	at de.unijena.bioinf.webapi.rest.RestAPI.lambda$checkConnection$12(RestAPI.java:230)
	at de.unijena.bioinf.rest.ProxyManager.consumeClient(ProxyManager.java:521)
	at de.unijena.bioinf.rest.ProxyManager.consumeClient(ProxyManager.java:515)
	at de.unijena.bioinf.webapi.rest.RestAPI.checkConnection(RestAPI.java:223)
	at de.unijena.bioinf.ms.frontend.subtools.login.LoginOptions$LoginWorkflow.determineAndCheckActiveSubscription(LoginOptions.java:336)
	at de.unijena.bioinf.ms.frontend.subtools.login.LoginOptions$LoginWorkflow.run(LoginOptions.java:224)
	at de.unijena.bioinf.ms.frontend.Run.compute(Run.java:61)
	at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.run(SiriusCLIApplication.java:131)
	at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.runMain(SiriusCLIApplication.java:73)
	at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.main(SiriusCLIApplication.java:53)

INFO    16:55:08 - CLI shut down hook: SIRIUS is cleaning up threads and shuts down...

**Comment by kuntuse** [comment]
The problem has been solved and I can now connect. It seems that this afternoon I was unable to connect to your server.
